version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: chorongyi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    container_name: chorongyi-backend
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend:/app

volumes:
  db_data:
